version: "3.8"
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=admin
    networks:
      - db-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/

networks:
  db-network:
    driver: bridge

volumes:
  postgres_data:
