# Generated by Django 4.0.5 on 2022-06-17 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
