# Generated by Django 4.0.5 on 2022-07-07 17:07

import daily_vocabulary.validators
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_daily_words',
            field=models.PositiveIntegerField(choices=[(1, 1), (3, 3), (5, 5), (10, 10), (15, 15), (20, 20), (50, 50)], default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=30, validators=[daily_vocabulary.validators.validate_at_least_one_lower_case, daily_vocabulary.validators.validate_at_least_one_upper_case, daily_vocabulary.validators.validate_at_least_one_digit, daily_vocabulary.validators.validate_at_least_one_special_character, daily_vocabulary.validators.validate_password_length]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[daily_vocabulary.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='word',
            name='created_at_local',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
