# Generated by Django 4.0.5 on 2022-07-07 17:10

import daily_vocabulary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0003_alter_user_num_daily_words_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=300, validators=[daily_vocabulary.validators.validate_at_least_one_lower_case, daily_vocabulary.validators.validate_at_least_one_upper_case, daily_vocabulary.validators.validate_at_least_one_digit, daily_vocabulary.validators.validate_at_least_one_special_character, daily_vocabulary.validators.validate_password_length]),
        ),
    ]
