# Generated by Django 4.0.5 on 2022-08-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_vocabulary', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
